config/routes.rb
Rails.application.routes.draw do

  get 'inicial' => 'gathers#new'
  get 'relatorio' => 'gathers#index'
  get 'dashboard' => 'dashboard#show'
  get 'relatorio' => 'gathers#index'
  root 'gathers#new'
  
  resources :gathers
  
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :gathers
end

app/models/cemetery.rb
class Cemetery < ActiveRecord::Base
  has_many :gathers
end

app/models/coffin.rb
class Coffin < ActiveRecord::Base
  has_many :gathers
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
	
	def graficoAgencias(intervalo)
		@agency = Agency.all
		g = Gruff::Bar.new(545)
		g.legend_font_size = 18
		g.title = "Número de vendas por agência"
		g.theme = { # Declare a custom theme
			:colors => %w(orange purple green blue red gray pink black brown violet), # colors can be described on hex values (#0f0f0f)
			:marker_color => 'black', # The horizontal lines color
			:background_colors => %w(white white) # you can use instead: :background_image => ‘some_image.png’
		}
		@agency.each do |a|
			g.data a.name, Gather.where(["agency_id = ?", a.id]).count
		end
		g.write("app/assets/images/charts/barra_agencias.png")
	end

	def graficoUrnas(intervalo)
		@coffin = Gather.group(:coffin_id).order('count_id DESC').limit(5).count(:id)
		g = Gruff::Pie.new(545)
		@coffin.each do |c|
			if c[0] != nil
				g.data Coffin.find(c[0]).name, c[1]
			end
		end		

		g.legend_font_size = 18
		g.title = "Urnas mais vendidas"
		g.theme = { # Declare a custom theme
			:colors => %w(orange purple green blue red gray pink black brown), # colors can be described on hex values (#0f0f0f)
			:marker_color => 'black', # The horizontal lines color
			:background_colors => %w(white white) # you can use instead: :background_image => ‘some_image.png’
		}
		g.title_margin = 0
		#g.hide_legend = true		
		g.write("app/assets/images/charts/pizza_urnas.png")
	end

	def graficoCemiterios(intervalo)
		@cemetery = Gather.group(:cemetery_id).order('count_id DESC').limit(5).count(:id)
		g = Gruff::Pie.new(545)
		@cemetery.each do |c|
			if c[0] != nil
				g.data Cemetery.find(c[0]).name, c[1]
			end
		end		

		g.legend_font_size = 18
		g.title = "Cemitérios mais contratados"
		g.theme = { # Declare a custom theme
			:colors => %w(orange purple green blue red gray pink black brown), # colors can be described on hex values (#0f0f0f)
			:marker_color => 'black', # The horizontal lines color
			:background_colors => %w(white white) # you can use instead: :background_image => ‘some_image.png’
		}
		g.title_margin = 0
		#g.hide_legend = true		
		g.write("app/assets/images/charts/pizza_cemiterios.png")
	end

	def graficoVelorios(intervalo)
		@funeral = Gather.group(:funeral_id).order('count_id DESC').all.count(:id)
		g = Gruff::Bar.new(545)
		g.legend_font_size = 18
		g.y_axis_increment = 10
		g.title = "Número de reservas por velório"
		g.theme = { # Declare a custom theme
			:colors => %w(orange purple green blue red gray pink black brown violet), # colors can be described on hex values (#0f0f0f)
			:marker_color => 'black', # The horizontal lines color
			:background_colors => %w(white white) # you can use instead: :background_image => ‘some_image.png’
		}		
		
		@funeral.each do |f|
			if f[0] != nil
				g.data Funeral.find(f[0]).name, f[1]
			end
		end
		g.sort = true
		g.write("app/assets/images/charts/linha_velorio.png")
	end

end

app/models/funeral.rb
class Funeral < ActiveRecord::Base
  has_many :gathers
end

app/models/gather.rb
class Gather < ActiveRecord::Base
  belongs_to :agency
  belongs_to :cemetery
  belongs_to :coffin
  belongs_to :funeral
  belongs_to :placeofdeath 
  
  validates :ncf, presence: true, length: { is: 7 }
  validates :agency_id, presence: true
  validates :deceased, presence: true
  validates :outside, presence: true
end

app/models/placeofdeath.rb
class Placeofdeath < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def show
		@dash = Dashboard.new
		@gather = Gather.all
		@intervalo = params[:interval]
		@dash.graficoAgencias(@intervalo)
		@dash.graficoUrnas(@intervalo)
		@dash.graficoVelorios(@intervalo)
		@dash.graficoCemiterios(@intervalo)
	end
end

app/controllers/gathers_controller.rb
class GathersController < ApplicationController 
  
  def index 
    @gather = Gather.all
    @agency = Agency.all
    @cemetery = Cemetery.all
    @coffin = Coffin.all
    @funeral = Funeral.all
    @placeofdeath = Placeofdeath.all
  end
  
  def show 
    @gather = Gather.find(params[:id])  
  end
  
  def new
    @gather = Gather.new   
  end  
  
  def edit    
  end
  
  def create
    @gather = Gather.new(params.require(:gather).permit(:ncf, :agency_id, :coffin_id, :deceased, :placeofdeath_id, :funeral_id, :cemetery_id, :healthcare, :namehc, :outside))    
    if @gather.save
      redirect_to @gather
    else
      render 'new'
    end
  end
  
  def destroy    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/gather_helper.rb
module GatherHelper
end

app/views/dashboard/show.html.erb
<!-- <%= image_tag("charts/test2.png", :alt => "Image missing") %> -->
<div id="form-container" class="col-md-10 col-md-offset-1">
	<div id="title-box">Bragi - Sistema de Coleta de Dados</div>
	
	<div class="row">
		<div class="col-md-6">			
			<%= image_tag("charts/barra_agencias.png", :alt => "Image missing") %>
		</div>
		<div class="col-md-6"><%= image_tag("charts/pizza_urnas.png", :alt => "Image missing") %></div>
	</div>
	<div class="row">
		<div class="col-md-6"><%= image_tag("charts/pizza_cemiterios.png",  :alt => "Image missing") %></div>
		<div class="col-md-6"><%= image_tag("charts/linha_velorio.png",  :alt => "Image missing") %></div>
		
	</div>

</div>

app/views/gathers/index.html.erb
<div id="form-container" class="col-md-10 col-md-offset-1">
					<div id="title-box">Bragi - Sistema de Coleta de Dados</div>
<div class="row">
	
	<table>
  <tr>
    <th>Horário da Criação</th>
    <th>Nº da Nota de Contratação </th>
    <th>Agência</th>
    <th>Modelo da Urna</th>
    <th>Nome do Falecido</th>
    <th>Local de Falecimento</th>
    <th>Local de Velório</th>
    <th>Local de Sepultamento/Cremação</th>
    <th>Tem Convênio?</th>
  </tr>
 
  <% @gather.each do |g| %>
    <tr>
      <td><%= g.created_at.to_s.chomp(' -0300') %></td>
      <td><%= g.ncf %></td>
      <td><%= g.agency.name %></td>
      <td><%= g.coffin.try(:name) %></td>
      <td><%= g.deceased %></td>
      <td><%= g.placeofdeath.try(:name) %></td>
      <td><%= g.funeral.try(:name) %></td>
      <td><%= g.cemetery.try(:name) %></td>
      <td><%= g.namehc unless g.healthcare == "Não" %></td>
  <% end %>
</table>
		
</div>
</div>

app/views/gathers/new.html.erb
<div id="form-container" class="col-md-6 col-md-offset-3">

<div id="title-box">Bragi - Sistema de Coleta de Dados</div>

<div id="form-restrainer">
<div class="row">
	<% if @gather.errors.any? %>
		<h4 align="center" style="color: red">Preencha todos os campos corretamente</h4>
	<% end %>
	
	<%= form_for @gather do |g| %>		
		<%= g.label :ncf, "Nº da Nota de Contratação" %>
		<%= g.text_field :ncf, class: 'form-control', maxlength: 7 %>		
	    
	    <%= g.label :agency_id, "Agência" %>		
		<%= g.select(:agency_id, Agency.all.collect{|a| [a.name, a.id]}, {include_blank: true}, {:class => 'form-control'}) %>			    
	    
	    <%= g.label :deceased, "Nome do Falecido" %>
	    <%= g.text_field :deceased, class: 'form-control' %>

	    <%= g.label :outside, "Corpo vindo de fora?" %>
	    <%= g.select(:outside, ['Sim', 'Não'], {include_blank: true}, { :class => 'form-control' }) %>

	    <div id="not_outside">
	    
		    <%= g.label :coffin_id, "Modelo da Urna" %>	    
		    <%= g.select(:coffin_id, Coffin.all.collect{|c| [c.name, c.id]}, {include_blank: true}, {:class => 'form-control'}) %>	    	    
		    	    
		    
		    <%= g.label :placeofdeath_id, "Local de Falecimento" %>
		    <%= g.select(:placeofdeath_id, Placeofdeath.all.collect{|p| [p.name, p.id]}, {include_blank: true}, {:class => 'form-control'}) %>	    
		    	    
		    <%= g.label :funeral_id, "Local de Velório" %>
		    <%= g.select(:funeral_id, Funeral.all.collect{|f| [f.name, f.id]}, {include_blank: true}, {:class => 'form-control'}) %>
		    	    
		    <%= g.label :cemetery_id, "Local de Sepultamento/Cremação" %>
		    <%= g.select(:cemetery_id, Cemetery.all.collect{|ce| [ce.name, ce.id]}, {include_blank: true}, {:class => 'form-control'}) %>
		    	    
		    <%= g.label :healthcare, "Convênio?" %>
		    <%= g.select(:healthcare, ['Sim', 'Não'], {include_blank: true}, { :class => 'form-control' }) %>
			
			<div id="healthcare_company">
		    	<%= g.label :namehc, "Qual empresa que presta o convênio?" %>
		    	<%= g.text_field :namehc, class: 'form-control' %>
		    </div>	    
			</div>
      <%= g.submit "Inserir Dados >", class: "button" %>			
	<% end %>
		
</div>
</div>
</div>

app/views/gathers/show.html.erb
<div id="form-container" class="col-md-6 col-md-offset-3">
					<div id="title-box">Sistema de Coleta de Dados</div>
<div id="form-restrainer">
<h2>Dados inseridos com sucesso!</h2>
<h2><%= link_to "Inserir novo cadastro", new_gather_url %></h2>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Bragi - Sistema de Coleta de dados das Agências</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="container" class="container-fluid">
			<div class="row">
				
					
						<%= yield %>
					
				</div>
			</div>
		</div>
	</body>
</html>